// ====== MOTS POUR LE JEU -mix start ======
// Lancé manuellement avec -mix start (owner uniquement)
// Les lettres du mot sont mélangées et affichées 60 secondes,
// répond 1 point au premier qui retrouve le mot d'origine

const MIX_WORDS = [
  { word: "ordinateur" },
  { word: "telephone" },
  { word: "maroc" },
  { word: "tanger" },
  { word: "discord" },
  { word: "musique" },
  { word: "football" },
  { word: "voiture" },
  { word: "cuisine" },
  { word: "montagne" },
  { word: "plage" },
  { word: "soleil" },
  { word: "voyage" },
  { word: "avion" },
  { word: "bateau" },
  { word: "jardin" },
  { word: "chocolat" },
  { word: "fromage" },
  { word: "ecole" },
  { word: "universite" },
  { word: "docteur" },
  { word: "police" },
  { word: "pompier" },
  { word: "ingenieur" },
  { word: "chanteur" },
  { word: "acteur" },
  { word: "peintre" },
  { word: "artiste" },
  { word: "histoire" },
  { word: "science" },
  { word: "planete" },
  { word: "espace" },
  { word: "etoile" },
  { word: "lumiere" },
  { word: "couleur" },
  { word: "nuage" },
  { word: "riviere" },
  { word: "foret" },
  { word: "desert" },
  { word: "oiseau" },
  { word: "poisson" },
  { word: "elephant" },
  { word: "tigre" },
  { word: "serpent" },
  { word: "papillon" },
  { word: "fenetre" },
  { word: "porte" },
  { word: "chaise" },
  { word: "clavier" }
];

module.exports = { MIX_WORDS };
